### PR TITLE
Made "sites" framework an optional requirement.

### PR DESCRIPTION
**Pull request by wWolfovich**
Made django.contrib.sites framework conditionaly an optional requirement.

### CODE REVIEW

**Comment by zlorf** [comment]
Good idea, give me a few days to review it.

**Comment by wWolfovich** [comment]
Will there be any decision?

**Comment by zlorf** [comment]
Man, I'm so busy now that I just cannot find a time to take a look at all issues and pull request (despite the fact that I'd very much like to)

**Comment by zlorf** [comment]
Thanks for patch and idea, sorry it took so long.
Finally I've decided to add a ``dbsettings.settings`` file containing detection of ``sites`` (useful with migrations) and to allow user to override default ``sites`` detection with DBSETTINGS_USE_SITES configuration variable.

**Pull request closed without merging**
