### PR TITLE
Changed post_syncdb for post_migrate (Django 1.9)

### PR DESCRIPTION
**Pull request by alons45**
Django 1.9 compatibility

### CODE REVIEW

**Comment by zlorf** [comment]
I wonder if it's possible to maintain backward compatibility. With this patch, app won't work with Django < 1.7 (due to lack of `post_migrate` signal)

**Comment by alons45** [comment]
aaah ok :octopus:

**Comment by zlorf** [comment]
I finally decided to drop compatibility with Django older than 1.7.

**Comment by alons45** [comment]
@zlorf thanks :dancer:

**Pull request merged**
