### PR TITLE
Drop legacy support for Python 2 and Django 1.x

### PR DESCRIPTION
**Pull request by Natureshadow**
With Python 2 leaving Earth forever with the first New Year rocket (https://pythonclock.org/), and the use of Django's version of the `six` module blocking the transition to Django 3.0, the use of six can be dropped altogether.

While at it, I rewrote `urls.py` to use `path()`. Technically, Django  1,11 is still in LTS, but that's not a reason to keep legacy code.

I raised the major version part to 1, so all dependency managers adhering to semver will no tpull the update if not told to. Users of legacy Django thus can just keep using 0.11, while everyone else can update to 1.1.

### CODE REVIEW

**Comment by zlorf** [comment]
Thank you!
Can you change the version to 1.0 instead of 1.1?

**Comment by Natureshadow** [comment]
> Thank you!
> Can you change the version to 1.0 instead of 1.1?

Oh, of course. Sorry I missed the comment.

Done!

**Comment by zlorf** [comment]
Actually, sorry for changing my mind, but can you remove the version bump from the commit? I'll increment it together with proper release notes when the other PR of yours will be merged too.

**Comment by Natureshadow** [comment]
Sure, done.

**Comment by Natureshadow** [comment]
Thanks for merging! I would really appreciate a new upload, with or without #51, because django-dbsettings right now is the only blocker in a Django 3.0 transition.

**Comment by zlorf** [comment]
I'll make a release today or tomorrow.

**Comment by Natureshadow** [comment]
Thanks :)!

(Today would give extra love, because it would allow me to close this case before leaving for holidays and not carry it over to next year ;)!)

**Comment by zlorf** [comment]
Done.

**Comment by mlier** [comment]
Hello,
I tried to run tox on that new release 1.0.0. Everything were right (py35, 36, 37, 38, django 20, 21, 22) but for Django 3. I had that error : 

`
ImportError: Failed to import test module: tests.tests
  File "/Users/.../django-dbsettings/tests/tests.py", line 7, in <module>
    from django.utils.functional import curry
ImportError: cannot import name 'curry' from 'django.utils.functional'
`

Seems that curry was removed from version 3.
Did I missed something ? How did you validate 1.0.0 version ?
Regards.

**Comment by zlorf** [comment]
Thanks for spotting this! On Christmas I was running tox on a laptop which did not contain Python 3.8 and I just assumed that it will work, as other versions did work.
Now fixed and retested on a desktop. I've made 1.0.1 release.

**Pull request merged**
