### PR TITLE
Added initial migration

### PR DESCRIPTION
**Pull request by Anton-Shutik**

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
Hi @zlorf !

I've just added initial migration to make it possible to setup the database from scratch. Table 'dbsettings_setting' creation was failing, because it required table 'django_site' to be created before. This PR fixed it.

Can you please merge this and make release ?

Thanks in advance!

**Comment by zlorf** [comment]
Hi!
I'll try to make 'sites' an optional requirement. I wonder if migrations can have conditional code.

**Comment by Anton-Shutik** [comment]
Cool! Thanks!
But anyway migration will be required :)  This just makes developers to use fork instead of app from repo or adding custom migration in their codebase like:

<code> MIGRATION_MODULES={'dbsettings': 'utils.db_migrations'}.</code>

So, I consider that this PR is ready to go before 'sites' stuff will be live.
What do you think about it ?

**Comment by zlorf** [comment]
I'll merge and release this in this week (with the ``sites`` stuff altogether).

**Comment by Anton-Shutik** [comment]
Great!
Thank you so much!

**Comment by Anton-Shutik** [comment]
Just added one more Value. It will not brake anything, just will cover cases when you need to store percent value in float.

**Comment by Anton-Shutik** [comment]
Hey @zlorf,
any issues I can help you with when merging this PR ?

**Comment by Anton-Shutik** [comment]
@zlorf Why dont you merge this PR ?

**Comment by zlorf** [comment]
Finally, a month later, I've managed to review the code, rewrite it and include.
There were some problems with running tests (that include their own model definition).
Moreover, migration content depends on whether ``sites`` are used or not (since they are optional).

**Pull request closed without merging**
