### PR TITLE
Added PercentFloatValue

### PR DESCRIPTION
**Pull request by Anton-Shutik**

### CODE REVIEW

**Comment by zlorf** [comment]
Why do feel this is needed? If you need a `float` data type, you can always cast `Decimal` to float. And `Decimal` is more accurate.

**Comment by Anton-Shutik** [comment]
Yep, but there is no PercentDecimalValue :) 
Actually I think PercentValue should be able to handle all of this

**Comment by Anton-Shutik** [comment]
Ohh wait, I though PercentValue handles int only. 

Sorry :)

**Comment by zlorf** [comment]
Maybe this should be more precisely stated in documentation.

**Comment by Anton-Shutik** [comment]
May that made me think so (from README):


PercentValue
 ------------

Similar to **IntegerValue** ...

**Pull request closed without merging**
