### PR TITLE
PercentValue widget rendering as string fixed

### PR DESCRIPTION
**Pull request by last-partizan**
also, added .swp to .gitignore file

### CODE REVIEW

**Comment by last-partizan** [comment]
Hey, @zlorf can you merge this pull-request?

PercentValue widget in your code was rendered as text, so i fixed it

**Comment by zlorf** [comment]
And now it renders as text as well, isn't it?

**Comment by last-partizan** [comment]
Now it renders as input widget + percent sign, as expected.

There was just missing mark_safe.

**Comment by last-partizan** [comment]
Here is what i'm talking about
before:


fixed:

**Comment by zlorf** [comment]
Thanks for spotting this bug! I've squashed commits to one and we don't really need this ``.swp`` thing in gitignore.

**Pull request closed without merging**
